version: 2

workflows:
    version: 2
    test-commit:
        jobs:
            - check
    test-daily:
        triggers:
            - schedule:
                  cron: "*/5 * * * *"
                  filters:
                      branches:
                          only: main
        jobs:
            - check

jobs:
    check:
        docker:
            - image: circleci/node:11-browsers
        steps:
            - checkout
            - run: node check.js
