version: 2

workflows:
    version: 2
    commit:
        jobs:
            - check
    interval:
        triggers:
            - schedule:
                  cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
                  filters:
                      branches:
                          only: main
        jobs:
            - check

jobs:
    check:
        docker:
            - image: circleci/node:11-browsers
        steps:
            - checkout
            - run: node check.js
