version: 2

workflows:
    version: 2
    commit:
        jobs:
            - xbox
            - mac
    interval:
        triggers:
            - schedule:
                  cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
                  filters:
                      branches:
                          only: main
        jobs:
            - xbox
            - mac
jobs:
    iphone:
        docker:
            - image: circleci/node:11-browsers
        steps:
            - checkout
            - run: node iphone.js
    xbox:
        docker:
            - image: circleci/node:11-browsers
        steps:
            - checkout
            - run: node xbox.js
    wallet:
        docker:
            - image: circleci/node:11-browsers
        steps:
            - checkout
            - run: node wallet.js
    mac:
        docker:
            - image: circleci/node:11-browsers
        steps:
            - checkout
            - run: node mac.js
